#服务器配置
server:
    port: 8888
    undertow:
        io-threads: 16
        worker-threads: 400
        buffer-size: 1024
        direct-buffers: true

spring:
    redis:
        #host: 60.160.190.129
        host: 192.168.12.109
        port: 6379
        password: wxfyyzy115
        database: 10
        ssl: false

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
        username: root
        password: root
        druid:
            validation-query: select 1
            validation-query-timeout: 2000
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            stat-view-servlet:
                enabled: true
                login-username: admin
                login-password: ylkj@65156676
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
                session-stat-enable: true
                session-stat-max-count: 10

# mybatis
mybatis-plus:
    mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
    type-handlers-package: org.springblade.common.handle
    typeAliasesPackage: org.springblade.**.entity
    global-config:
        banner: false
        db-config:
            id-type: id_worker
            insert-strategy: not_null
            update-strategy: not_null
            select-strategy: not_empty
            table-underline: true
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

swagger:
    title: 数据管理工具平台 接口文档系统
    description: 数据管理工具平台 接口文档系统
    version: 1.0.0
    license: Powered By ylkj
    license-url: www.cnynld.com
    terms-of-service-url: www.cnynld.com

#blade配置
blade:
    xss:
        enabled: true
        skip-url:
            - /blade-chat/weixin
            - /blade-desk/notice/submit
    #本地文件上传
    file:
        remote-mode: true
        upload-domain: http://localhost:8999
        remote-path: /usr/share/nginx/html
    log:
        request:
            enabled: false
    mybatis-plus:
        sql-log: false

#feign 配置
feign:
    httpclient:
        enabled: false
    okhttp:
        enabled: true
    hystrix:
        enabled: true


